import { DashboardToolbar } from "./components/DashboardToolbar";
import { DatasetHeader } from "./components/DatasetHeader";
import { LeaderboardPagination } from "./components/LeaderboardPagination";
import { TierBadge } from "./components/TierBadge";
import { AssetImage } from "./components/AssetImage";
import { duelPressDetailHref } from "./duelPressRoute";
import { duelPressMetricConfig } from "./duelPressRegistry";
import { DUEL_PRESS_METRIC_KEYS, type DuelPressLeaderboardPayload, type DuelPressPlayerCore, type DuelPressSearch, type DuelPressSortKey } from "../api/duelPressTypes";
import type { DatasetMeta, DatasetRouteState, LeaderboardOptions } from "./types";
type Props = { payload: DuelPressLeaderboardPayload; dataset: DatasetRouteState; options?: LeaderboardOptions; search: DuelPressSearch; refreshing: boolean; onRefresh(): void; onDatasetChange(state: DatasetRouteState): void; onSearchChange(search: DuelPressSearch, replace?: boolean): void; onPageChange(page: number): void; warning?: React.ReactNode };
const Score = ({ player, metric }: { player: DuelPressPlayerCore; metric: typeof DUEL_PRESS_METRIC_KEYS[number] }) => { const config = duelPressMetricConfig[metric]; return <span tabIndex={0} title={config.detail} aria-label={`${config.label} ${player.stats[metric]} out of 100. ${config.detail}`} className="inline-flex min-h-9 min-w-11 items-center justify-center rounded border border-white/15 font-mono text-xs font-bold focus-visible:ring-2 focus-visible:ring-lime-300">{player.stats[metric]}</span>; };
export default function DuelPressLeaderboardDashboard({ payload, dataset, options, search, refreshing, onRefresh, onDatasetChange, onSearchChange, onPageChange, warning }: Props) {
  const update = (patch: Partial<DuelPressSearch>, replace = false) => onSearchChange({ ...search, ...patch, page: patch.page ?? 1 }, replace);
  const sort = (key: DuelPressSortKey) => update({ sort: key, direction: search.sort === key && search.direction === "desc" ? "asc" : "desc", page: 1 });
  const meta = payload.meta as unknown as DatasetMeta; const total = payload.meta.totalItems; const start = payload.players.length ? (payload.meta.page - 1) * 50 + 1 : 0; const end = start ? start + payload.players.length - 1 : 0;
  return <main id="main-content" aria-busy={refreshing} className="min-h-screen bg-[#080b0c] text-zinc-100"><div className="mx-auto max-w-[1580px] px-3 py-5 sm:px-6 lg:px-8"><DatasetHeader meta={meta} visibleCount={payload.players.length} refreshing={refreshing} onRefresh={onRefresh} state={dataset} options={options} onStateChange={onDatasetChange} />{warning}<DashboardToolbar isRefreshing={refreshing} query={search.q} role={search.role === "all" ? "ALL" : search.role} position={search.position} ageBand={search.ageBand === "u25" ? "23-25" : search.ageBand} minutesBand={search.minutesBand} positionCapability="supported" ageCapability="supported" minutesCapability="supported" watchOnly={false} watchCount={0} watchAvailable={false} resultLabel={`${payload.players.length} shown · ${total} results`} hasFilters={Boolean(search.q || search.role !== "all" || search.position !== "ALL" || search.ageBand !== "all" || search.minutesBand !== "all" || search.sort !== "score" || search.direction !== "desc")} players={payload.players} dataset={dataset} onPlayerSuggestionSelect={(player) => window.location.assign(duelPressDetailHref(player.id, dataset))} onQueryChange={(q) => update({ q }, true)} onRoleChange={(role) => update({ role: role === "Type A" || role === "Type B" ? role : "all" })} onPositionChange={(position) => update({ position })} onAgeBandChange={(ageBand) => update({ ageBand: ageBand === "23-25" ? "u25" : ageBand })} onMinutesBandChange={(minutesBand) => update({ minutesBand })} onWatchOnlyChange={() => undefined} onReset={() => onSearchChange({ page: 1, pageSize: 50, q: "", role: "all", position: "ALL", ageBand: "all", minutesBand: "all", sort: "score", direction: "desc" })} />
    <p className="mb-3 text-xs text-zinc-400">{start ? `${start}–${end} of ${total} players` : `0 of ${total} players`}</p>
    {payload.players.length > 0 && <nav aria-label="Duel-press player details" className="mb-3 flex flex-wrap gap-2">{payload.players.map((player) => <a key={player.id} href={duelPressDetailHref(player.id, dataset)} className="min-h-9 rounded border border-white/10 px-2 py-2 text-[10px] text-lime-200 hover:underline">{player.name} detail</a>)}</nav>}
    {payload.players.length ? <><section aria-label="Mobile duel-press leaderboard" className="grid gap-2 md:hidden">{payload.players.map((player) => <article key={player.id} className="rounded-lg border border-white/10 bg-[#0d1112] p-3"><div className="flex min-w-0 items-center gap-3"><AssetImage src={player.face} alt="" kind="face" fallbackLabel={player.name} width={44} height={44} className="h-11 w-11 rounded object-cover"/><div className="min-w-0 flex-1"><b className="block truncate">{player.name}</b><span className="text-xs text-zinc-400">#{player.rank} · {player.club.name}</span></div><div><b className="font-mono">{player.score}</b><TierBadge tier={player.tier}/></div></div><div className="mt-3 grid grid-cols-3 gap-2">{DUEL_PRESS_METRIC_KEYS.map((metric) => <div key={metric} className="min-w-0 rounded bg-black/20 p-2 text-center"><span className="mb-1 block break-words text-[9px] text-zinc-400">{duelPressMetricConfig[metric].short}</span><Score player={player} metric={metric}/></div>)}</div></article>)}</section><div className="hidden overflow-x-auto md:block"><table className="min-w-[1180px] w-full border-separate border-spacing-0"><caption className="sr-only">Duel-press leaderboard</caption><thead><tr><th className="sticky left-0 z-20 bg-[#080b0c] p-2 text-left">Player</th><th><button onClick={() => sort("score")}>Score</button></th>{DUEL_PRESS_METRIC_KEYS.map((metric) => <th key={metric} title={duelPressMetricConfig[metric].detail} className="min-w-28 p-2"><button aria-label={`Sort by ${duelPressMetricConfig[metric].label}`} onClick={() => sort(metric)}>{duelPressMetricConfig[metric].short}</button></th>)}</tr></thead><tbody>{payload.players.map((player) => <tr key={player.id}><th scope="row" className="sticky left-0 z-10 bg-[#0d1112] p-2 text-left"><span className="block">#{player.rank} {player.name}</span><span className="text-xs font-normal text-zinc-400">{player.club.name}</span></th><td className="p-2 text-center"><b>{player.score}</b><TierBadge tier={player.tier}/></td>{DUEL_PRESS_METRIC_KEYS.map((metric) => <td key={metric} className="p-2 text-center"><Score player={player} metric={metric}/></td>)}</tr>)}</tbody></table></div><LeaderboardPagination page={payload.meta.page} total={total} pageSize={50} pending={refreshing} onPageChange={onPageChange}/></> : <section className="rounded border border-dashed border-white/15 p-8 text-center text-zinc-400">{payload.meta.page > payload.meta.totalPages && total > 0 ? "Requested page is beyond the available results." : "No players match these filters."}</section>}
  </div></main>;
}
