import { useEffect, useState } from "react";
import { parseMessiApiConfig } from "../api/env";
import { fetchPlayerDetail } from "../api/leaderboardsApi";
import type { Player } from "../dashboard/types";

export function StaticRoute() {
 const path = window.location.pathname;
 if (path === "/about/messi") return <main className="grid min-h-screen place-items-center bg-[#080b0c] p-6 text-zinc-100"><article className="max-w-2xl rounded-xl border border-white/10 bg-[#101415] p-7"><a href="/" className="text-lime-300">← Leaderboard</a><h1 className="mt-5 text-3xl font-black">M.E.S.S.I. metrics</h1><p className="mt-3 text-zinc-400">The index combines outside-box shooting, in-box shooting, dribbling, aerial and ground duels, and off-the-ball movement. Scores remain the existing algorithm; dashboard labels improve readability only.</p></article></main>;
 if (path === "/compare") return <main className="grid min-h-screen place-items-center bg-[#080b0c] p-6 text-zinc-100"><article className="max-w-xl rounded-xl border border-white/10 bg-[#101415] p-7"><a href="/" className="text-lime-300">← Leaderboard</a><h1 className="mt-5 text-3xl font-black">Player comparison</h1><p className="mt-3 text-zinc-400">Select up to four players from the leaderboard to compare their six sector scores.</p></article></main>;
 const id = Number(path.split("/")[2]); return <PlayerDetail id={id} />;
}
function PlayerDetail({ id }: { id: number }) { const [player, setPlayer] = useState<Player>(); const [error, setError] = useState(""); useEffect(() => { if (!Number.isInteger(id) || id <= 0) { setError("Player not found"); return; } const controller = new AbortController(); try { const config = parseMessiApiConfig(import.meta.env, import.meta.env.MODE); fetchPlayerDetail(config, id, { season: new URLSearchParams(window.location.search).get("season") ?? config.season, mode: "league", scope: config.scope, competition: "all" }, controller.signal).then(setPlayer).catch(() => setError("Player details are unavailable for this dataset.")); } catch { setError("Dashboard API configuration is unavailable."); } return () => controller.abort(); }, [id]); return <main className="grid min-h-screen place-items-center bg-[#080b0c] p-6 text-zinc-100"><article className="w-full max-w-xl rounded-xl border border-white/10 bg-[#101415] p-7"><a href="/" className="text-lime-300">← Leaderboard</a>{error ? <p role="alert" className="mt-5 text-amber-300">{error}</p> : !player ? <p className="mt-5 text-zinc-400">Loading player profile…</p> : <><h1 className="mt-5 text-3xl font-black">{player.name}</h1><p className="mt-2 text-zinc-400">{player.club.name} · {player.league.name} · {player.position}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm">{Object.entries(player.stats).map(([key, value]) => <div key={key} className="rounded bg-black/20 p-3"><span className="text-zinc-500">{key}</span><b className="float-right text-lime-300">{value}</b></div>)}</div></>}</article></main>; }
