import { useEffect, useRef, useState } from "react";
import { parseMessiApiConfig, type MessiApiConfig } from "../api/env";
import { MessiApiError } from "../api/errors";
import { fetchPlayerDetail } from "../api/leaderboardsApi";
import { datasetFromSearch, datasetHref } from "../dashboard/datasetRoute";
import { metricConfig, metricKeys } from "../dashboard/scoutingConfig";
import type { DatasetRouteState, Player } from "../dashboard/types";
function currentDataset(config?: MessiApiConfig): DatasetRouteState { return datasetFromSearch(window.location.search, { season: config?.season ?? "2025/2026", mode: "league", scope: (config?.scope ?? 7) as 3 | 5 | 7, competition: "all" }); }
function ContextBadge({ dataset }: { dataset: DatasetRouteState }) { return <span className="inline-flex rounded border border-lime-300/30 bg-lime-300/10 px-2 py-1 text-[10px] font-bold text-lime-200">{dataset.mode === "europe" ? `Europe · ${dataset.competition.toUpperCase()}` : `League · ${dataset.scope} leagues`} · {dataset.season}</span>; }
function BackLink({ dataset }: { dataset: DatasetRouteState }) { return <a href={datasetHref("/", dataset)} className="text-lime-300 hover:underline">← Leaderboard</a>; }
function Page({ children }: { children: React.ReactNode }) { return <main id="main-content" className="grid min-h-screen place-items-center bg-[#080b0c] p-6 text-zinc-100"><article className="w-full max-w-2xl rounded-xl border border-white/10 bg-[#101415] p-7">{children}</article></main>; }
function FocusTitle({ children }: { children: React.ReactNode }) { const ref = useRef<HTMLHeadingElement>(null); useEffect(() => { ref.current?.focus(); }, []); return <h1 ref={ref} tabIndex={-1} className="mt-5 text-3xl font-black outline-none">{children}</h1>; }
function compareSelection(): { id: number; name: string }[] { try { const value: unknown = JSON.parse(sessionStorage.getItem("messi-comparison-selection") || "[]"); return Array.isArray(value) ? value.filter((item): item is { id: number; name: string } => typeof item?.id === "number" && typeof item?.name === "string") : []; } catch { return []; } }
export function StaticRoute() { const path = window.location.pathname; let config: MessiApiConfig | undefined; try { config = parseMessiApiConfig(import.meta.env, import.meta.env.MODE); } catch { /* detail explains configuration failure */ } const dataset = currentDataset(config); if (path === "/about/messi") return <Page><FocusTitle>M.E.S.S.I. metrics</FocusTitle><p className="mt-3 text-zinc-400">The index combines outside-box shooting, in-box shooting, dribbling, aerial and ground duels, and off-the-ball movement. Scores remain the existing algorithm; dashboard labels improve readability only.</p><a href="/" className="mt-6 inline-flex min-h-11 items-center text-lime-300 hover:underline">Browse leaderboard</a></Page>; if (path === "/compare") { const selected = compareSelection(); return <Page><ContextBadge dataset={dataset} /><FocusTitle>Player comparison</FocusTitle>{selected.length ? <p className="mt-3 text-zinc-300">Selected: {selected.map((player) => player.name).join(", ")}</p> : <p className="mt-3 text-zinc-400">No players selected yet.</p>}<p className="mt-3 text-zinc-400">Comparison analysis is not available from the current API. This page intentionally does not invent comparison results.</p><div className="mt-6"><BackLink dataset={dataset} /></div></Page>; } return <PlayerDetail id={Number(path.split("/")[2])} dataset={dataset} config={config} />; }
function PlayerDetail({ id, dataset, config }: { id: number; dataset: DatasetRouteState; config?: MessiApiConfig }) { const [player, setPlayer] = useState<Player>(); const [error, setError] = useState<"network" | "not-found" | "config">(); const [retry, setRetry] = useState(0); useEffect(() => { if (!Number.isInteger(id) || id <= 0) { setError("not-found"); return; } if (!config) { setError("config"); return; } const controller = new AbortController(); setPlayer(undefined); setError(undefined); fetchPlayerDetail(config, id, dataset, controller.signal).then(setPlayer).catch((cause: unknown) => { if (!controller.signal.aborted) setError(cause instanceof MessiApiError && cause.status === 404 ? "not-found" : "network"); }); return () => controller.abort(); }, [config, dataset, id, retry]); return <Page><ContextBadge dataset={dataset} />{!player && !error && <><FocusTitle>Player profile</FocusTitle><div aria-busy="true" className="mt-5 space-y-3"><div className="h-7 w-48 animate-pulse rounded bg-white/10" /><div className="h-24 animate-pulse rounded bg-white/10" /></div></>}{error && <><FocusTitle>{error === "not-found" ? "Player not found" : "Player details unavailable"}</FocusTitle><p role="alert" className="mt-3 text-zinc-400">{error === "not-found" ? "This player is not available in the selected dataset." : error === "config" ? "Dashboard API configuration is unavailable." : "We could not load this player profile. Check your connection and try again."}</p>{error !== "not-found" && <button type="button" onClick={() => setRetry((value) => value + 1)} className="mt-5 min-h-11 rounded border border-lime-300/40 px-4 text-lime-300">Retry</button>}</>}{player && <><FocusTitle>{player.name}</FocusTitle><p className="mt-2 text-zinc-400">{player.club.name} · {player.league.name} · {player.position}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm">{metricKeys.map((key) => <div key={key} className="rounded bg-black/20 p-3"><span className="text-zinc-500">{metricConfig[key].label}</span><b className="float-right text-lime-300">{player.stats[key]}</b></div>)}</div></>}<div className="mt-6"><BackLink dataset={dataset} /></div></Page>; }
