import { useEffect, useRef, useState } from "react";
import { parseMessiApiConfig, type MessiApiConfig } from "../api/env";
import { MessiApiError } from "../api/errors";
import { fetchComparison, fetchPlayerDetail } from "../api/leaderboardsApi";
import { datasetFromSearch, datasetHref } from "../dashboard/datasetRoute";
import { metricConfig, metricKeys } from "../dashboard/scoutingConfig";
import type { DatasetRouteState, PlayerAnalysis, PlayerComparison, PlayerDetail } from "../dashboard/types";

function currentDataset(config?: MessiApiConfig): DatasetRouteState { return datasetFromSearch(window.location.search, { season: config?.season ?? "2025/2026", mode: "league", scope: (config?.scope ?? 7) as 3 | 5 | 7, competition: "all" }); }
function ContextBadge({ dataset }: { dataset: DatasetRouteState }) { return <span className="inline-flex rounded border border-lime-300/30 bg-lime-300/10 px-2 py-1 text-[10px] font-bold text-lime-200">{dataset.mode === "europe" ? `Europe · ${dataset.competition.toUpperCase()}` : `League · ${dataset.scope} leagues`} · {dataset.season}</span>; }
function BackLink({ dataset }: { dataset: DatasetRouteState }) { return <a href={datasetHref("/", dataset)} className="text-lime-300 hover:underline">← Leaderboard</a>; }
function Page({ children }: { children: React.ReactNode }) { return <main id="main-content" className="grid min-h-screen place-items-center bg-[#080b0c] p-6 text-zinc-100"><article className="w-full max-w-3xl rounded-xl border border-white/10 bg-[#101415] p-7">{children}</article></main>; }
function FocusTitle({ children }: { children: React.ReactNode }) { const ref = useRef<HTMLHeadingElement>(null); useEffect(() => { ref.current?.focus(); }, []); return <h1 ref={ref} tabIndex={-1} className="mt-5 text-3xl font-black outline-none">{children}</h1>; }
function idsFromUrl(): number[] | undefined { const raw = new URLSearchParams(window.location.search).get("players"); if (!raw) return []; const ids = raw.split(",").map(Number); return ids.length === 2 && ids.every((id) => Number.isInteger(id) && id > 0) && new Set(ids).size === ids.length ? ids : undefined; }
function AnalysisSummary({ analysis }: { analysis?: PlayerAnalysis }) {
  if (!analysis) return <section className="mt-6 rounded border border-white/10 bg-black/20 p-4" aria-label="Server analysis"><h2 className="font-bold">Server analysis</h2><p className="mt-2 text-sm text-zinc-400">The current API returned no analysis for this player. No client-side analysis has been invented.</p></section>;
  const metrics = Object.entries(analysis.rawMetrics).filter(([, value]) => value !== null).slice(0, 8);
  return <section className="mt-6 rounded border border-white/10 bg-black/20 p-4" aria-label="Server analysis"><h2 className="font-bold">Server analysis</h2><p className="mt-2 text-sm text-zinc-300">Score {analysis.score.value} · cohort {analysis.score.population}</p><div className="mt-4 grid gap-4 md:grid-cols-2"><MetricTable title="Volume profile" axes={analysis.volumeRadar.axes} /><MetricTable title="Ratio profile" axes={analysis.ratioRadar.axes} /></div><p className="mt-4 text-xs text-zinc-400">Spatial data: {analysis.spatial.available ? `${analysis.spatial.heatmapPointCount} server-provided points` : "unavailable for this context"}.</p>{metrics.length > 0 && <dl className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{metrics.map(([key, value]) => <div key={key} className="rounded bg-white/[.03] p-2"><dt className="truncate text-zinc-500">{key}</dt><dd className="font-bold text-zinc-200">{String(value)}</dd></div>)}</dl>}</section>;
}
function MetricTable({ title, axes }: { title: string; axes: PlayerAnalysis["volumeRadar"]["axes"] }) { return <div><h3 className="text-sm font-bold text-zinc-200">{title}</h3><table className="mt-2 w-full text-left text-xs"><thead className="text-zinc-500"><tr><th>Metric</th><th className="text-right">Score</th><th className="text-right">Percentile</th></tr></thead><tbody>{axes.map((axis) => <tr key={axis.id} className="border-t border-white/10"><th className="py-1 font-medium text-zinc-300">{axis.label}</th><td className="py-1 text-right text-lime-300">{axis.score}</td><td className="py-1 text-right text-zinc-400">{axis.percentile ?? "—"}</td></tr>)}</tbody></table></div>; }

export function StaticRoute() {
  const path = window.location.pathname; let config: MessiApiConfig | undefined;
  try { config = parseMessiApiConfig(import.meta.env, import.meta.env.MODE); } catch { /* individual pages explain config failure */ }
  const dataset = currentDataset(config);
  if (path === "/about/messi") return <Page><FocusTitle>M.E.S.S.I. metrics</FocusTitle><p className="mt-3 text-zinc-400">The index combines outside-box shooting, in-box shooting, dribbling, aerial and ground duels, and off-the-ball movement. Scores remain the existing algorithm; dashboard labels improve readability only.</p><a href="/" className="mt-6 inline-flex min-h-11 items-center text-lime-300 hover:underline">Browse leaderboard</a></Page>;
  if (path === "/compare") return <CompareRoute dataset={dataset} config={config} ids={idsFromUrl()} />;
  return <PlayerDetailRoute id={Number(path.split("/")[2])} dataset={dataset} config={config} />;
}

function PlayerDetailRoute({ id, dataset, config }: { id: number; dataset: DatasetRouteState; config?: MessiApiConfig }) {
  const [detail, setDetail] = useState<PlayerDetail>(); const [error, setError] = useState<"network" | "not-found" | "config">(); const [retry, setRetry] = useState(0);
  useEffect(() => { if (!Number.isInteger(id) || id <= 0) { setError("not-found"); return; } if (!config) { setError("config"); return; } const controller = new AbortController(); setDetail(undefined); setError(undefined); fetchPlayerDetail(config, id, dataset, controller.signal).then(setDetail).catch((cause: unknown) => { if (!controller.signal.aborted) setError(cause instanceof MessiApiError && cause.status === 404 ? "not-found" : "network"); }); return () => controller.abort(); }, [config, dataset, id, retry]);
  const player = detail?.player; const analysis = detail?.analysis;
  return <Page><ContextBadge dataset={dataset} />{!player && !error && <><FocusTitle>Player profile</FocusTitle><div aria-busy="true" className="mt-5 space-y-3"><div className="h-7 w-48 animate-pulse rounded bg-white/10" /><div className="h-24 animate-pulse rounded bg-white/10" /></div></>}{error && <><FocusTitle>{error === "not-found" ? "Player not found" : "Player details unavailable"}</FocusTitle><p role="alert" className="mt-3 text-zinc-400">{error === "not-found" ? "This player is not available in the selected dataset." : error === "config" ? "Dashboard API configuration is unavailable." : "We could not load this player profile. Check your connection and try again."}</p>{error !== "not-found" && <button type="button" onClick={() => setRetry((value) => value + 1)} className="mt-5 min-h-11 rounded border border-lime-300/40 px-4 text-lime-300">Retry</button>}</>}{player && <><FocusTitle>{player.name}</FocusTitle><p className="mt-2 text-zinc-400">{player.club.name} · {player.league.name} · {player.position}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm">{metricKeys.map((key) => <div key={key} className="rounded bg-black/20 p-3"><span className="text-zinc-500">{metricConfig[key].label}</span><b className="float-right text-lime-300">{player.stats[key]}</b></div>)}</div><AnalysisSummary analysis={analysis} /></>}<div className="mt-6"><BackLink dataset={dataset} /></div></Page>;
}

function CompareRoute({ dataset, config, ids }: { dataset: DatasetRouteState; config?: MessiApiConfig; ids: number[] | undefined }) {
  const [comparison, setComparison] = useState<PlayerComparison>(); const [error, setError] = useState<"network" | "config">(); const [retry, setRetry] = useState(0);
  useEffect(() => { if (!ids || ids.length !== 2 || !config) return; const controller = new AbortController(); setComparison(undefined); setError(undefined); fetchComparison(config, ids, dataset, controller.signal).then(setComparison).catch(() => { if (!controller.signal.aborted) setError("network"); }); return () => controller.abort(); }, [config, dataset, ids?.join(","), retry]);
  if (ids === undefined) return <Page><ContextBadge dataset={dataset} /><FocusTitle>Player comparison</FocusTitle><p role="alert" className="mt-3 text-zinc-400">Choose two distinct players before opening comparison.</p><div className="mt-6"><BackLink dataset={dataset} /></div></Page>;
  if (!ids.length) return <Page><ContextBadge dataset={dataset} /><FocusTitle>Player comparison</FocusTitle><p className="mt-3 text-zinc-400">Select two players from the leaderboard to request a server comparison.</p><div className="mt-6"><BackLink dataset={dataset} /></div></Page>;
  if (!config || error) return <Page><ContextBadge dataset={dataset} /><FocusTitle>Player comparison unavailable</FocusTitle><p role="alert" className="mt-3 text-zinc-400">{!config ? "Dashboard API configuration is unavailable." : "The server comparison could not be loaded."}</p>{config && <button type="button" onClick={() => setRetry((value) => value + 1)} className="mt-5 min-h-11 rounded border border-lime-300/40 px-4 text-lime-300">Retry</button>}<div className="mt-6"><BackLink dataset={dataset} /></div></Page>;
  return <Page><ContextBadge dataset={dataset} /><FocusTitle>Player comparison</FocusTitle>{!comparison ? <div aria-busy="true" className="mt-5 h-28 animate-pulse rounded bg-white/10" /> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{comparison.players.map(({ player, analysis }) => <section key={player.id} className="rounded border border-white/10 bg-black/20 p-4"><h2 className="font-bold">{player.name}</h2><p className="text-xs text-zinc-500">{player.club.name} · {player.position}</p><p className="mt-2 text-sm text-lime-300">M.E.S.S.I. {player.score}</p><AnalysisSummary analysis={analysis} /></section>)}</div>}<div className="mt-6"><BackLink dataset={dataset} /></div></Page>;
}
