// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BenchmarkRadarV2Panel } from "./BenchmarkRadarV2";
import type { BenchmarkRadarV2 } from "../api/benchmarkRadarV2Contracts";

const ids = ["outsideShot", "boxThreat", "dangerZone", "combinedDuel", "spaceControl", "forwardPress"] as const;
afterEach(cleanup);
function data(state: "observed" | "low_sample" | "unavailable" = "observed"): BenchmarkRadarV2 { const ref = state === "unavailable" ? { score:null,population:8,state,reason:"position_label_not_player_role" } : { score:54.43,population:state === "low_sample" ? 7 : 300,state,reason:state === "low_sample" ? "position_population_below_minimum" : null }; const axes=ids.map((id)=>({id,label:id,radarOnlyRepresentation:false,representationLabel:null,components:[{id:`${id}-raw`,label:"Server raw",value:1,unit:"per90",direction:"higher_is_better",source:"player_season_total",state:"observed",percentileScore:60,formulaId:null,formulaVersion:null,zeroAttemptsFloor:false}],player:{score:70,state:"observed"},globalAverage:{score:49,population:1057,state:"observed",reason:null},positionAverage:ref})); return {sourceContext:{playerId:1,idNamespace:"fotmob",season:"2025/2026",mode:"league",scope:7,competition:null},benchmarkContext:{season:"2025/2026",mode:"league",scope:8,competition:null,label:"8-league avg"},positionReference:{rawPosition:state==="unavailable"?"Coach":"Left Wing-Back",comparisonKey:"test",minimumPopulation:20,population:ref.population,state,reason:ref.reason},volume:{kind:"volume",scoreFormulaId:"server",scoreFormulaVersion:"v2",axes},ratio:{kind:"ratio",scoreFormulaId:"server",scoreFormulaVersion:"v2",axes}} as BenchmarkRadarV2; }
describe("BenchmarkRadarV2Panel",()=>{
  it("renders player, global, and observed-position series with server labels and populations",()=>{render(<BenchmarkRadarV2Panel state={{kind:"ready",data:data()}} playerName="Player" onRetry={vi.fn()}/>); expect(document.querySelectorAll('[data-series="player"]').length).toBe(2); expect(document.querySelectorAll('[data-series="global"]').length).toBe(2); expect(document.querySelectorAll('[data-series="position"][visibility="visible"]').length).toBe(2); expect(screen.getAllByText("공간 점유").length).toBeGreaterThan(0); expect(screen.queryByText("오프 더 볼")).toBeNull(); expect(screen.getAllByText(/N=1057/).length).toBeGreaterThan(0); expect(screen.getAllByText(/N=300/).length).toBeGreaterThan(0);});
  it("keeps the position series and actual population for low sample",()=>{render(<BenchmarkRadarV2Panel state={{kind:"ready",data:data("low_sample")}} playerName="Player" onRetry={vi.fn()}/>); expect(document.querySelectorAll('[data-series="position"][visibility="visible"]').length).toBe(2); expect(screen.getAllByText(/저표본 포지션 · N=7/).length).toBe(2);});
  it("hides unavailable position series and does not replace it with the global value",()=>{render(<BenchmarkRadarV2Panel state={{kind:"ready",data:data("unavailable")}} playerName="Player" onRetry={vi.fn()}/>); expect(document.querySelectorAll('[data-series="position"][visibility="hidden"]').length).toBe(2); expect(screen.getAllByText(/동일 포지션 평균 없음: position_label_not_player_role/).length).toBe(2); expect(screen.getAllByText(/포지션 — · N=8/).length).toBe(12);});
});
