import { getScoreBand } from "../dashboard/scoutingConfig";
import type { DuelPressDetailReadout, DuelPressDetailReadoutEnvelope } from "../api/duelPressDetailReadoutContracts";

const categoryCopy: Record<DuelPressDetailReadoutEnvelope["categories"][number]["id"], { short: string; label: string }> = {
  outsideShot: { short: "01", label: "박스 밖 슈팅" }, boxThreat: { short: "02", label: "박스 안 슈팅" }, dangerZone: { short: "03", label: "온볼 전개 영향력" }, combinedDuel: { short: "04", label: "통합 경합" }, spaceControl: { short: "05", label: "오프 더 볼" }, forwardPress: { short: "06", label: "전방 압박 효율" },
};
const directions = { higher_is_better: "높을수록 좋음", lower_is_better: "낮을수록 좋음", neutral: "중립 맥락" } as const;
const units = { count: "회", per90: "/90", goals: "골", percent: "%", score: "점" } as const;
const source = { player_season_total: "선수 시즌 원자료", league_per90_fallback: "리그 /90 대체 원자료", tactical_ratio_static: "전술 비율 정적 자료", server_derived: "서버 산출", unavailable: "제공 불가" } as const;
const state = { observed: "관측", server_derived: "서버 산출", imputed: "대체", unavailable: "제공 불가", legacy_partial: "부분 제공" } as const;
const ground = new Set(["groundDuelAttempts", "groundWonPer90", "groundLostPer90", "duelMarginPer90", "groundDuelWinRate"]);

function number(value: number) { return Number.isInteger(value) ? String(value) : value.toFixed(2).replace(/0+$/, "").replace(/\.$/, ""); }
function comparison(readout: DuelPressDetailReadout) { const item = readout.comparison; if (item.state === "available") return `중앙값 ${number(item.median!)} · ${item.rank}/${item.population} · ${number(item.percentile!)}백분위`; if (item.state === "unavailable" && item.median !== null) return `중앙값 ${number(item.median)} · 비교 제공 불가`; return item.state === "not_applicable" ? "비교 비적용" : "비교 제공 불가"; }
function ReadoutRows({ items }: { items: readonly DuelPressDetailReadout[] }) { return <dl className="mt-3 divide-y divide-white/10 border-t border-white/10 text-[11px] leading-4"><dt className="sr-only">서버 측정값</dt>{items.map((item) => <div key={item.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-x-2 py-2"><dt className="min-w-0 font-medium text-zinc-300">{item.label}<span className="ml-1 text-zinc-500">({directions[item.direction]})</span></dt><dd className="text-right font-mono tabular-nums text-zinc-100">{item.value === null ? "제공 불가" : <>{number(item.value)} <span className="font-sans text-zinc-400">{units[item.unit]}</span></>}</dd><dd className="col-span-2 mt-0.5 text-[10px] text-zinc-500">{state[item.state]} · {source[item.source]} · {comparison(item)}{item.missingComponents?.length ? ` · 누락: ${item.missingComponents.join(", ")}` : ""}</dd></div>)}</dl>; }
function ScoreComparison({ category }: { category: DuelPressDetailReadoutEnvelope["categories"][number] }) { const item = category.comparison; return <p className="mt-1 text-[10px] text-zinc-500">{item.state === "available" ? `코호트 ${item.rank}/${item.population} · ${number(item.percentile!)}백분위` : item.state === "unavailable" ? "카테고리 비교 제공 불가" : "카테고리 비교 비적용"}</p>; }
function CategoryCard({ category }: { category: DuelPressDetailReadoutEnvelope["categories"][number] }) { const copy = categoryCopy[category.id]; const band = category.score === null ? undefined : getScoreBand(category.score); const groups = category.id === "combinedDuel" ? [["지상 경합", category.readouts.filter((item) => ground.has(item.id))], ["공중 경합", category.readouts.filter((item) => !ground.has(item.id))]] as const : [[undefined, category.readouts]] as const;
  return <article className="min-w-0 rounded-xl border border-white/10 bg-[#101415] p-3 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black tracking-[0.18em] text-zinc-500">{copy.short}</p><h3 className="text-sm font-black text-white">{copy.label}</h3></div><div className="text-right"><b className={`text-2xl font-black tabular-nums ${band?.dotClassName ?? "text-zinc-500"}`}>{category.score === null ? "제공 불가" : number(category.score)}</b>{category.score !== null && <span className="ml-1 text-[10px] text-zinc-500">/100</span>}<p className={`mt-0.5 text-[10px] ${category.scoreState === "imputed" ? "text-amber-200" : "text-zinc-500"}`}>{category.scoreState === "imputed" ? `대체: ${category.imputedComponents.join(", ")}` : category.scoreState === "unavailable" ? "점수 제공 불가" : "관측 점수"}</p></div></div>{category.score !== null && <div role="progressbar" aria-label={`${copy.label} 서버 점수`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={category.score} className="mt-3 h-1.5 overflow-hidden rounded bg-white/10"><span className={`block h-full rounded ${band!.dotClassName}`} style={{ width: `${category.score}%` }} /></div>}<ScoreComparison category={category}/>{groups.map(([title, items]) => <section key={title ?? "all"} aria-label={title} className={title ? "mt-3" : undefined}>{title && <h4 className="border-b border-white/10 pb-1 text-xs font-bold text-zinc-200">{title}</h4>}<ReadoutRows items={items}/></section>)}</article>; }
function AuxiliaryModule({ readout, copy }: { readout: DuelPressDetailReadout; copy: string }) { const value = readout.value; return <article className="min-w-0 rounded-xl border border-white/10 bg-[#101415] p-4"><h3 className="font-black text-white">{readout.id === "netProgressionPer90" ? "순수 전진 기여도" : "득점 운 · 상대 선방"}</h3><p className="mt-1 text-xs text-zinc-400">{copy}</p><div aria-hidden="true" className="mt-5 h-2 rounded bg-gradient-to-r from-rose-400/35 via-zinc-500/30 to-sky-300/35"/><dl className="mt-4 space-y-1 text-xs"><div className="flex justify-between gap-3"><dt className="text-zinc-500">값</dt><dd className="font-mono font-bold tabular-nums">{value === null ? "제공 불가" : `${number(value)} ${units[readout.unit]}`}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">비교</dt><dd className="text-right">{comparison(readout)}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-500">상태/출처</dt><dd>{state[readout.state]} · {source[readout.source]}</dd></div></dl></article>; }

export function DuelPressDetailReadoutBoard({ data }: { data: DuelPressDetailReadoutEnvelope }) { return <section aria-label="Duel press detailed stats board" className="min-w-0"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><h2 className="text-lg font-black">상세 스탯 보드</h2><p className="text-xs text-zinc-400">동일 컨텍스트의 서버 제공 읽기값입니다.</p></div><span className="text-[10px] tracking-wider text-zinc-500">DUEL-PRESS-V1 · DETAIL-READOUT-V1</span></div><div data-layout="detail-readout-grid" className="mt-4 grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{data.categories.map((category) => <CategoryCard key={category.id} category={category}/>)}</div><section aria-labelledby="auxiliary-measurements-heading" className="mt-6 border-t border-white/15 pt-5"><h2 id="auxiliary-measurements-heading" className="text-sm font-black">보조 측정값</h2><div data-layout="auxiliary-measurements" className="mt-3 grid gap-3 md:grid-cols-2"><AuxiliaryModule readout={data.contextIndicators[0]} copy="M.E.S.S.I. 섹터 점수가 아닌 순수 전진 기여 측정값입니다."/><AuxiliaryModule readout={data.contextIndicators[1]} copy="득점 − xGOT의 맥락 지표이며, 양수/음수는 단독 우열이나 M.E.S.S.I. 섹터 점수를 뜻하지 않습니다."/></div></section></section>; }

export function DuelPressDetailReadoutUnavailable({ message, onRetry, loading }: { message?: string; onRetry?: () => void; loading?: boolean }) { return <section aria-label="Duel press detailed stats board" aria-busy={loading || undefined} className="rounded-xl border border-amber-300/30 bg-amber-300/10 p-4"><h2 className="font-black">상세 스탯 보드 {loading ? "불러오는 중" : "제공 불가"}</h2><p role={loading ? "status" : "alert"} className="mt-2 text-sm text-zinc-300">{loading ? "동일 컨텍스트의 서버 읽기값을 불러오는 중입니다." : message ?? "이 컨텍스트의 상세 스탯 읽기값을 제공할 수 없습니다."}</p>{onRetry && !loading && <button type="button" onClick={onRetry} className="mt-4 min-h-11 rounded border border-lime-300/40 px-4 text-sm text-lime-200">상세 스탯 다시 시도</button>}</section>; }
