// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { finalThirdShotMapFixture } from "../test/fixtures/finalThirdShotMap";
import { PLAN_VERTICAL_TRANSFORM_Y, POSITIONAL_DEPTH_BOUNDARIES, projectPlan } from "./SpatialPitch";
const hook = vi.hoisted(() => ({ value: undefined as unknown })); vi.mock("./useFinalThirdShotMap", () => ({ useFinalThirdShotMap: () => hook.value }));
import { FinalThirdShootingMap } from "./FinalThirdShootingMap";
afterEach(cleanup);
describe("Final Third Shot Chart", () => { it("uses shared cropped geometry and equal taxonomy footprints", () => { const key = "first"; hook.value = { state: { kind: "partial", data: finalThirdShotMapFixture, key }, resourceKey: key, retry: vi.fn() }; const { container } = render(<FinalThirdShootingMap playerId={194165} dataset={{ season: "2025/2026", mode: "league", scope: 8, competition: "all" }} />); expect(container.querySelector("[data-shared-plan-pitch]")).toBeInTheDocument(); expect(container.querySelector("[data-final-third-vertical-transform]")).toHaveAttribute("transform", `matrix(0 -1 1 0 0 ${PLAN_VERTICAL_TRANSFORM_Y})`); const [x, y, width, height] = container.querySelector("[data-final-third-pitch]")!.getAttribute("viewBox")!.split(" ").map(Number); expect(y).toBe(PLAN_VERTICAL_TRANSFORM_Y - projectPlan({ x: 100, y: 50 }).x); expect(y + height).toBe(PLAN_VERTICAL_TRANSFORM_Y - projectPlan({ x: POSITIONAL_DEPTH_BOUNDARIES[4], y: 50 }).x); expect(x).toBe(projectPlan({ x: 50, y: 100 }).y); expect(width).toBe(projectPlan({ x: 50, y: 0 }).y - projectPlan({ x: 50, y: 100 }).y); const paths = [...container.querySelectorAll("[data-zone-outer]")].map((node) => node.getAttribute("d")); expect(new Set(paths.map((path) => path!.replace(/-?\d+(?:\.\d+)?/g, "#"))).size).toBe(1); });
  it("renders endpoint shape geometry and supports roving tab keys", () => { const key = "first"; const rich = structuredClone(finalThirdShotMapFixture); rich.data.shots = [rich.data.shots[0], { ...rich.data.shots[0], shotId: "target", status: "on_target", xg: 0 }, { ...rich.data.shots[0], shotId: "off", status: "off_target", xg: null }, { ...rich.data.shots[0], shotId: "block", status: "blocked", xg: .3 }] as never; hook.value = { state: { kind: "partial", data: rich, key }, resourceKey: key, retry: vi.fn() }; const { container } = render(<FinalThirdShootingMap playerId={194165} dataset={{ season: "2025/2026", mode: "league", scope: 8, competition: "all" }} />); const pitch = screen.getByRole("tab", { name: "Pitch" }), mouth = screen.getByRole("tab", { name: "Goal-Mouth" }); fireEvent.keyDown(pitch, { key: "End" }); expect(mouth).toHaveAttribute("aria-selected", "true"); expect(container.querySelector("[data-marker-shape='diamond']")).toBeInTheDocument(); expect(container.querySelector("[data-marker-shape='circle']")).toBeInTheDocument(); expect(container.querySelector("[data-marker-shape='cross']")).toBeInTheDocument(); expect(container.querySelector("[data-marker-shape='square']")).toBeInTheDocument(); expect(container.querySelector("[data-goal-mouth-shot='off']")).toHaveAttribute("data-xg-size", "unavailable"); expect(container.querySelector("[data-goal-mouth-shot='target']")).toHaveAttribute("data-xg-size", "observed"); });
  it("renders endpoint-unavailable audit IDs by default", () => { const key = "audit"; hook.value = { state: { kind: "partial", data: finalThirdShotMapFixture, key }, resourceKey: key, retry: vi.fn() }; render(<FinalThirdShootingMap playerId={194165} dataset={{ season: "2025/2026", mode: "league", scope: 8, competition: "all" }} />); fireEvent.click(screen.getByRole("tab", { name: "Goal-Mouth" })); expect(screen.getByRole("heading", { name: "1 endpoint not plotted" })).toBeVisible(); expect(screen.getByLabelText("Unplotted endpoint audit list")).toHaveTextContent("blocked-1 — blocked, blocked_has_no_goal_mouth_endpoint"); });
  it("synchronously hides an old keyed payload and resets its view", () => { const oldKey = "old", newKey = "new"; hook.value = { state: { kind: "partial", data: finalThirdShotMapFixture, key: oldKey }, resourceKey: oldKey, retry: vi.fn() }; const rendered = render(<FinalThirdShootingMap playerId={194165} dataset={{ season: "2025/2026", mode: "league", scope: 8, competition: "all" }} />); fireEvent.click(screen.getByRole("tab", { name: "Goal-Mouth" })); hook.value = { state: { kind: "partial", data: finalThirdShotMapFixture, key: oldKey }, resourceKey: newKey, retry: vi.fn() }; rendered.rerender(<FinalThirdShootingMap playerId={194165} dataset={{ season: "2024/2025", mode: "league", scope: 8, competition: "all" }} />); expect(rendered.container.querySelector("[data-zone-id]")).toBeNull(); expect(screen.getByRole("status")).toHaveAttribute("aria-busy", "true"); }); });
