import type { DuelPressPlayerCore, PressingRawSource } from "../../api/duelPressTypes";
import { DUEL_PRESS_METRIC_KEYS } from "../../api/duelPressTypes";
import { duelPressMetricConfig } from "../duelPressRegistry";
import { getScoreBand } from "../scoutingConfig";
const sourceLabel = (source: PressingRawSource) => source === "player_season_total" ? "player season total" : source === "league_per90_fallback" ? "league per-90 fallback" : "unavailable";
const RawValue = ({ label, value, source }: { label: string; value: number | null; source: PressingRawSource }) => <div className="min-w-0 rounded border border-white/10 p-3"><dt className="break-words text-xs text-zinc-400">{label}</dt><dd aria-label={value === null ? `${label}: 데이터 없음, 측정된 0이 아님, ${sourceLabel(source)}` : `${label}: ${value.toFixed(2)}, ${sourceLabel(source)}`} className="mt-1 font-mono text-sm">{value === null ? "-" : value.toFixed(2)}</dd><p className="mt-1 text-[10px] text-zinc-500">{value === null ? "데이터 없음 · 측정된 0이 아님" : sourceLabel(source)}</p></div>;
export function DuelPressDetailMetrics({ player }: { player: DuelPressPlayerCore }) {
  const raw = player.pressingRawMetrics;
  return <section aria-label="Duel and pressing assessment"><div className="grid grid-cols-3 gap-2 md:grid-cols-6">{DUEL_PRESS_METRIC_KEYS.map((key) => { const config = duelPressMetricConfig[key]; const band = getScoreBand(player.stats[key]); return <div key={key} title={config.detail} aria-label={`${config.label} ${player.stats[key]} out of 100. ${config.detail}`} className={`min-w-0 rounded border p-2 text-center ${band.className}`}><span className="block break-words text-[10px]">{config.short}</span><b className="font-mono">{player.stats[key]}</b></div>; })}</div><dl className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><RawValue label="Recoveries per 90" value={raw.recoveriesPer90} source={raw.recoveriesSource} /><RawValue label="Final-third possessions won per 90" value={raw.finalThirdPossessionsWonPer90} source={raw.finalThirdPossessionsWonSource} /></dl><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4" aria-label="Explanatory components">{Object.entries(player.components).map(([key, value]) => <div key={key} className="min-w-0 rounded border border-white/10 p-2"><span className="break-words text-[10px] text-zinc-400">{key}</span><b className="block font-mono">{value}</b></div>)}</div><p className="mt-2 text-[10px] text-zinc-500">구성요소는 지표 설명용이며 전체 점수를 브라우저에서 다시 계산하지 않습니다.</p></section>;
}
