import type { DatasetRouteState, Tier } from "../types";
import type { PlayerIdentityData } from "./PlayerIdentity";
import { MetricScore } from "./MetricScore";
import { PlayerIdentity } from "./PlayerIdentity";
import { TierBadge } from "./TierBadge";

export type LeaderboardPresentationPlayer<K extends string> = PlayerIdentityData & {
  rank: number; age: number | null; minutes: number; tier: Tier; score: number; stats: Record<K, number>;
};
export type MetricPresentation = { label: string; short: string; detail: string };
export type MetricPresentationRegistry<K extends string> = Record<K, MetricPresentation>;
export type PresentationSort = { key: string; direction: "asc" | "desc" };
export type WatchPresentation<P> = {
  available: boolean; isWatched(player: P): boolean; onToggle(player: P): void; unavailableLabel?: string;
};

type SharedProps<K extends string, P extends LeaderboardPresentationPlayer<K>> = {
  players: readonly P[]; dataset?: DatasetRouteState; metricKeys: readonly K[]; metricRegistry: MetricPresentationRegistry<K>;
  sort: PresentationSort; onMetricSort(key: "score" | K): void; detailHref?(player: P): string; watch: WatchPresentation<P>;
};

export function LeaderboardTableColumns<K extends string>({ metricKeys }: { metricKeys: readonly K[] }) {
  return <colgroup><col className="w-[330px]" /><col className="w-40" /><col className="w-24" />{metricKeys.map((key) => <col key={key} className="w-24" />)}<col className="w-24" /><col className="w-16" /><col className="w-24" /></colgroup>;
}
const order = (sort: PresentationSort, key: string) => sort.key === key ? (sort.direction === "asc" ? "ascending" : "descending") : "none";
function SortMetric<K extends string>({ metric, config, sort, onMetricSort }: { metric: K; config: MetricPresentation; sort: PresentationSort; onMetricSort(key: "score" | K): void }) { const active = sort.key === metric; return <button type="button" aria-label={`Sort by ${config.label}${active ? ` ${order(sort, metric)}` : ""}`} onClick={() => onMetricSort(metric)} className="min-h-11 px-1 text-[9px] uppercase tracking-wider hover:text-lime-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-300">{config.label}{active ? (sort.direction === "asc" ? " ↑" : " ↓") : ""}</button>; }
function SortScore<K extends string>({ sort, onMetricSort }: { sort: PresentationSort; onMetricSort(key: "score" | K): void }) { const active = sort.key === "score"; return <button type="button" aria-label={`Sort by M.E.S.S.I. score ${active ? order(sort, "score") : "descending"}`} onClick={() => onMetricSort("score")} className="min-h-11 px-1 text-[9px] uppercase tracking-wider hover:text-lime-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-300">M.E.S.S.I.{active ? (sort.direction === "asc" ? " ↑" : " ↓") : ""}</button>; }
export function LeaderboardTableHeader<K extends string>({ metricKeys, metricRegistry, sort, onMetricSort }: Pick<SharedProps<K, LeaderboardPresentationPlayer<K>>, "metricKeys" | "metricRegistry" | "sort" | "onMetricSort">) { return <thead className="sticky top-0 z-30 bg-[#0b0e0f]/95"><tr className="h-11 border-b border-white/10 text-[9px] uppercase tracking-wider text-zinc-500"><th scope="col" className="sticky left-0 z-10 bg-[#0b0e0f] px-3 text-left">Player profile</th><th scope="col">Tier</th><th scope="col" aria-sort={order(sort, "score")}><SortScore sort={sort} onMetricSort={onMetricSort} /></th>{metricKeys.map((key) => <th key={key} scope="col" aria-sort={order(sort, key)}><SortMetric metric={key} config={metricRegistry[key]} sort={sort} onMetricSort={onMetricSort} /></th>)}<th scope="col" className="text-right">Minutes</th><th scope="col">Age</th><th scope="col">Watch</th></tr></thead>; }

export function LeaderboardPlayerTable<K extends string, P extends LeaderboardPresentationPlayer<K>>({ players, dataset, metricKeys, metricRegistry, sort, onMetricSort, detailHref, watch }: SharedProps<K, P>) {
  const unavailable = watch.unavailableLabel ?? "준비 중";
  return <section className="hidden rounded-lg border border-white/10 bg-[#0d1112] md:block"><div className="overflow-x-auto"><table className="w-full min-w-[1340px] table-fixed border-collapse"><caption className="sr-only">Scouting dataset players and six sector scores</caption><LeaderboardTableColumns metricKeys={metricKeys} /><LeaderboardTableHeader metricKeys={metricKeys} metricRegistry={metricRegistry} sort={sort} onMetricSort={onMetricSort} /><tbody>{players.map((player) => <tr key={player.id} className="group h-[72px] border-b border-white/[.07] hover:bg-lime-300/[.04]"><th scope="row" className="sticky left-0 z-10 bg-[#0d1112] px-3 text-left group-hover:bg-[#121916]"><div className="flex items-center gap-3"><span className="w-6 font-mono text-[10px] text-zinc-600">{String(player.rank).padStart(2, "0")}</span><PlayerIdentity player={player} dataset={dataset} detailHref={detailHref?.(player)} /></div></th><td className="px-1 text-center"><TierBadge tier={player.tier} compact /></td><td className="text-center font-mono text-lg font-black">{player.score.toFixed(1)}</td>{metricKeys.map((key) => <td key={key}><MetricScore playerId={player.id} metric={key} value={player.stats[key]} surface="table" presentation={metricRegistry[key]} /></td>)}<td className="px-2 text-right font-mono text-xs">{player.minutes.toLocaleString()}</td><td title={player.age === null ? "Birth date unavailable" : undefined} className="text-center font-mono text-xs">{player.age ?? "—"}</td><td className="text-center"><button disabled={!watch.available} title={!watch.available ? unavailable : undefined} className={watch.available ? "min-h-11 min-w-11 rounded focus-visible:ring-2 focus-visible:ring-lime-300" : "min-h-11 min-w-11 rounded text-[10px] text-zinc-500 disabled:cursor-not-allowed"} onClick={watch.available ? () => watch.onToggle(player) : undefined} aria-pressed={watch.available ? watch.isWatched(player) : false} aria-label={`${player.name} watchlist${watch.available ? "" : `, ${unavailable}`}`}>{watch.available ? (watch.isWatched(player) ? "✓" : "+") : unavailable}</button></td></tr>)}</tbody></table></div></section>;
}

export function LeaderboardPlayerCardList<K extends string, P extends LeaderboardPresentationPlayer<K>>({ players, dataset, metricKeys, metricRegistry, sort, onMetricSort, detailHref, watch }: SharedProps<K, P>) {
  const scoreOrder = sort.key === "score" && sort.direction === "asc" ? "ascending" : "descending";
  const unavailable = watch.unavailableLabel ?? "준비 중";
  return <section className="space-y-2 md:hidden" aria-label="Mobile player list"><button type="button" onClick={() => onMetricSort("score")} aria-label={`Sort by M.E.S.S.I. score ${scoreOrder}`} className="min-h-11 rounded border border-white/10 bg-[#0d1112] px-3 text-xs font-bold text-zinc-300">M.E.S.S.I. score {scoreOrder === "ascending" ? "↑" : "↓"}</button>{players.map((player) => <article key={player.id} className="rounded-lg border border-white/10 bg-[#0d1112] p-3"><div className="flex items-start gap-2"><span className="pt-1 font-mono text-[10px] text-zinc-600">{player.rank}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><PlayerIdentity player={player} dataset={dataset} mobile detailHref={detailHref?.(player)} /><div className="text-right"><b className="font-mono text-lg">{player.score.toFixed(1)}</b><div><TierBadge tier={player.tier} compact /></div></div></div></div></div><div className="mt-3 grid grid-cols-3 gap-2">{metricKeys.map((key) => <div key={key} className="rounded bg-black/20 p-2 text-center"><p className="mb-1 text-[9px] text-zinc-500">{metricRegistry[key].short}</p><MetricScore playerId={player.id} metric={key} value={player.stats[key]} surface="mobile" compact presentation={metricRegistry[key]} /></div>)}</div><div className="mt-3"><button disabled={!watch.available} title={!watch.available ? unavailable : undefined} aria-label={watch.available ? undefined : `${player.name} watchlist, ${unavailable}`} className={watch.available ? "min-h-11 w-full rounded border border-white/10" : "min-h-11 w-full rounded border border-white/10 text-zinc-500 disabled:cursor-not-allowed"} onClick={watch.available ? () => watch.onToggle(player) : undefined} aria-pressed={watch.available ? watch.isWatched(player) : false}>{watch.available ? (watch.isWatched(player) ? "Saved to watchlist" : "Watch") : unavailable}</button></div></article>)}</section>;
}
