import { metricConfig, metricKeys } from "../scoutingConfig";
import type { DatasetRouteState, MetricKey, Player, SortKey, SortState } from "../types";
import { contextFromDataset, watchlistKey } from "../watchlistStorage";
import { MetricScore } from "./MetricScore";
import { PlayerIdentity } from "./PlayerIdentity";
import { TierBadge } from "./TierBadge";

type Props = { players: readonly Player[]; dataset?: DatasetRouteState; watchedKeys?: ReadonlySet<string>; watchedIds?: ReadonlySet<number>; sort: SortState; onMetricSort(key: SortKey): void; onToggleWatch(player: Player): void; comparedIds?: ReadonlySet<number>; onToggleCompare?(player: Player): void };
export function TableColumns() { return <colgroup><col className="w-[330px]" /><col className="w-40" /><col className="w-24" />{metricKeys.map((key) => <col key={key} className="w-24" />)}<col className="w-24" /><col className="w-16" /><col className="w-24" /></colgroup>; }
const order = (sort: SortState, key: SortKey) => sort.key === key ? (sort.direction === "asc" ? "ascending" : "descending") : "none";
function SortMetric({ metric, sort, onMetricSort }: { metric: MetricKey; sort: SortState; onMetricSort(key: SortKey): void }) { const active = sort.key === metric; return <button type="button" aria-label={`Sort by ${metricConfig[metric].label}${active ? ` ${order(sort, metric)}` : ""}`} onClick={() => onMetricSort(metric)} className="min-h-11 px-1 text-[9px] uppercase tracking-wider hover:text-lime-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-300">{metricConfig[metric].label}{active ? (sort.direction === "asc" ? " ↑" : " ↓") : ""}</button>; }
function SortScore({ sort, onMetricSort }: { sort: SortState; onMetricSort(key: SortKey): void }) { const active = sort.key === "score"; return <button type="button" aria-label={`Sort by M.E.S.S.I. score ${active ? order(sort, "score") : "descending"}`} onClick={() => onMetricSort("score")} className="min-h-11 px-1 text-[9px] uppercase tracking-wider hover:text-lime-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-300">M.E.S.S.I.{active ? (sort.direction === "asc" ? " ↑" : " ↓") : ""}</button>; }
export function TableHeader({ sort, onMetricSort }: { sort: SortState; onMetricSort(key: SortKey): void }) { return <thead className="sticky top-0 z-30 bg-[#0b0e0f]/95"><tr className="h-11 border-b border-white/10 text-[9px] uppercase tracking-wider text-zinc-500"><th scope="col" className="sticky left-0 z-10 bg-[#0b0e0f] px-3 text-left">Player profile</th><th scope="col">Tier</th><th scope="col" aria-sort={order(sort, "score")}><SortScore sort={sort} onMetricSort={onMetricSort} /></th>{metricKeys.map((key) => <th key={key} scope="col" aria-sort={order(sort, key)}><SortMetric metric={key} sort={sort} onMetricSort={onMetricSort} /></th>)}<th scope="col" className="text-right">Minutes</th><th scope="col">Age</th><th scope="col">Watch</th></tr></thead>; }
export function PlayerTable({ players, dataset, watchedKeys, watchedIds, sort, onMetricSort, onToggleWatch }: Props) {
  const context = dataset ? contextFromDataset(dataset) : undefined;
  const isWatched = (player: Player) => context ? Boolean(watchedKeys?.has(watchlistKey(player.id, context))) : Boolean(watchedIds?.has(player.id));
  return <section className="hidden rounded-lg border border-white/10 bg-[#0d1112] md:block"><div className="overflow-x-auto"><table className="w-full min-w-[1340px] table-fixed border-collapse"><caption className="sr-only">Scouting dataset players and six sector scores</caption><TableColumns /><TableHeader sort={sort} onMetricSort={onMetricSort} /><tbody>{players.map((player) => <tr key={player.id} className="group h-[72px] border-b border-white/[.07] hover:bg-lime-300/[.04]"><th scope="row" className="sticky left-0 z-10 bg-[#0d1112] px-3 text-left group-hover:bg-[#121916]"><div className="flex items-center gap-3"><span className="w-6 font-mono text-[10px] text-zinc-600">{String(player.rank).padStart(2, "0")}</span><PlayerIdentity player={player} dataset={dataset} /></div></th><td className="px-1 text-center"><TierBadge tier={player.tier} compact /></td><td className="text-center font-mono text-lg font-black">{player.score.toFixed(1)}</td>{metricKeys.map((key) => <td key={key}><MetricScore playerId={player.id} metric={key} value={player.stats[key]} surface="table" /></td>)}<td className="px-2 text-right font-mono text-xs">{player.minutes.toLocaleString()}</td><td title={player.age === null ? "Birth date unavailable" : undefined} className="text-center font-mono text-xs">{player.age ?? "—"}</td><td className="text-center"><button className="min-h-11 min-w-11 rounded focus-visible:ring-2 focus-visible:ring-lime-300" onClick={() => onToggleWatch(player)} aria-pressed={isWatched(player)} aria-label={`${player.name} watchlist`}>{isWatched(player) ? "✓" : "+"}</button></td></tr>)}</tbody></table></div></section>;
}
