import { metricConfig, metricKeys, resolveTierPresentation } from "../scoutingConfig";
import type { SortState } from "../types";
import type { WatchlistRow } from "../watchlistViewModel";
import { datasetStateFromWatchlistEntry, watchlistContextLabel } from "../watchlistViewModel";
import { enabledLegacyHref, legacyDetailHref } from "../../navigation/legacyHandoff";
import { datasetHref } from "../datasetRoute";
import type { QualityDisplay } from "../dataQualityViewModel";
import { DataQualityBadge } from "./DataQualityBadge";
import { MetricScore } from "./MetricScore";
import { TierBadge } from "./TierBadge";

type Props = { rows: readonly WatchlistRow[]; qualityByKey?: Readonly<Record<string, QualityDisplay>>; onRemove(key: string): void; onRetry(): void; sort?: SortState; onScoreSort?(): void };
function profileHref(row: WatchlistRow) { const state = datasetStateFromWatchlistEntry(row.entry); return enabledLegacyHref(legacyDetailHref(row.entry.playerId, { name: row.profile.name, clubName: row.profile.clubName }, state) ?? "") ?? datasetHref(`/players/${row.entry.playerId}`, state); }
function sourceBadge(row: WatchlistRow) { const legacy = row.profile.tier && resolveTierPresentation(row.profile.tier).taxonomy === "legacy-v1" ? " · Legacy tiers" : ""; if (row.source === "current") return null; if (row.source === "snapshot") return <span title="Stored score at save time; current rank is not recomputed." className="rounded border border-amber-300/25 bg-amber-300/10 px-2 py-1 text-[9px] font-bold text-amber-100">저장 시점 스냅샷{legacy}</span>; return <span className="rounded border border-white/15 px-2 py-1 text-[9px] font-bold text-zinc-400">이전 형식 저장</span>; }
export function WatchlistCardList({ rows, qualityByKey = {}, onRemove, onRetry, sort = { key: "score", direction: "desc" }, onScoreSort }: Props) {
  const scoreOrder = sort.key === "score" && sort.direction === "asc" ? "ascending" : "descending";
  return <section className="space-y-2 md:hidden" aria-label="Saved player contexts"><button type="button" onClick={onScoreSort} aria-label={`Sort by M.E.S.S.I. score ${scoreOrder}`} className="min-h-11 rounded border border-white/10 bg-[#0d1112] px-3 text-xs font-bold text-zinc-300">M.E.S.S.I. score {scoreOrder === "ascending" ? "↑" : "↓"}</button>{rows.map((row) => {
    const profile = row.profile;
    if (row.source === "legacy-partial") return <article key={row.key} className="rounded-lg border border-amber-300/20 bg-[#0d1112] p-3"><a href={profileHref(row)} className="block truncate font-bold hover:text-lime-300">{profile.name}</a><p className="mt-1 text-xs text-zinc-400">이전 형식으로 저장되어 지표·나이·출전 시간이 없습니다.</p><p className="mt-1 text-[10px] text-zinc-500">{watchlistContextLabel(row.entry)}</p><div className="mt-3 grid grid-cols-3 gap-2"><button type="button" onClick={onRetry} className="min-h-11 rounded border border-white/10 text-xs">Retry Resolve</button><a href={profileHref(row)} className="inline-flex min-h-11 items-center justify-center rounded border border-white/10 text-xs">Detail</a><button type="button" aria-pressed="true" aria-label={`Remove ${profile.name} saved context`} title={`Remove ${profile.name} saved context`} onClick={() => onRemove(row.key)} className="min-h-11 min-w-11 rounded border border-white/10">✓</button></div></article>;
    const snapshot = row.source === "snapshot"; const quality = row.source === "current" ? qualityByKey[row.key] : undefined;
    return <article key={row.key} className="rounded-lg border border-white/10 bg-[#0d1112] p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><a href={profileHref(row)} className="block truncate font-bold hover:text-lime-300">{profile.name}</a><p className="truncate text-[10px] text-zinc-500">{profile.position} · {profile.clubName}</p><div className="mt-2 flex flex-wrap gap-1"><span className="inline-flex rounded border border-lime-300/25 bg-lime-300/10 px-2 py-1 text-[9px] font-bold text-lime-100">{watchlistContextLabel(row.entry)}</span>{sourceBadge(row)}</div></div><div className="text-right"><b className="font-mono text-lg">{profile.score?.toFixed(1)}</b><DataQualityBadge quality={quality} /><div>{profile.tier && <TierBadge tier={profile.tier} compact />}</div></div></div><div className="mt-3 grid grid-cols-3 gap-2">{metricKeys.map((key) => <div key={key} className="rounded bg-black/20 p-2 text-center"><p className="mb-1 text-[9px] text-zinc-500">{metricConfig[key].short}</p><MetricScore playerId={row.entry.playerId} metric={key} value={profile.stats![key]!} surface="mobile" compact snapshot={snapshot} quality={quality} /></div>)}</div><p className="mt-3 text-[10px] text-zinc-500">{snapshot ? "Stored scores at save time; current ranks are not recomputed." : ""}</p><div className="mt-2 grid grid-cols-2 gap-2"><a href={profileHref(row)} className="inline-flex min-h-11 items-center justify-center rounded border border-white/10 text-xs">Detail</a><button type="button" aria-pressed="true" aria-label={`Remove ${profile.name} saved context`} className="min-h-11 min-w-11 rounded border border-white/10" onClick={() => onRemove(row.key)}>✓</button></div></article>;
  })}</section>;
}
