import { z } from "zod";

export const benchmarkRadarV2AxisIds = ["outsideShot", "boxThreat", "dangerZone", "combinedDuel", "spaceControl", "forwardPress"] as const;
const score = z.number().finite().min(0).max(100);
const context = z.object({ season: z.string().regex(/^\d{4}\/\d{4}$/), mode: z.enum(["league", "europe"]), scope: z.union([z.literal(3), z.literal(5), z.literal(7), z.literal(8), z.null()]), competition: z.enum(["all", "ucl", "uel", "uecl"]).nullable() }).strict();
const reference = z.object({ score: score.nullable(), population: z.number().int().nonnegative(), state: z.enum(["observed", "low_sample", "unavailable"]), reason: z.string().nullable() }).strict();
const component = z.object({ id: z.string().min(1), label: z.string().min(1), value: z.number().finite().nullable(), unit: z.string().min(1), direction: z.enum(["higher_is_better", "lower_is_better", "neutral", "diverging"]), source: z.string().min(1), state: z.string().min(1), percentileScore: z.number().int().min(0).max(99).nullable(), formulaId: z.string().nullable(), formulaVersion: z.string().nullable(), zeroAttemptsFloor: z.boolean() }).strict();
const axis = (id: typeof benchmarkRadarV2AxisIds[number]) => z.object({ id: z.literal(id), label: z.string().min(1), radarOnlyRepresentation: z.boolean(), representationLabel: z.string().nullable(), components: z.array(component).min(1), player: z.object({ score: score.nullable(), state: z.string().min(1) }).strict(), globalAverage: reference, positionAverage: reference }).strict();
const axes = z.tuple(benchmarkRadarV2AxisIds.map(axis) as [ReturnType<typeof axis>, ReturnType<typeof axis>, ReturnType<typeof axis>, ReturnType<typeof axis>, ReturnType<typeof axis>, ReturnType<typeof axis>]);
const series = z.object({ kind: z.enum(["volume", "ratio"]), scoreFormulaId: z.string().min(1), scoreFormulaVersion: z.string().min(1), axes }).strict();
export const benchmarkRadarV2EnvelopeSchema = z.object({ schemaVersion: z.literal("1.0.0"), benchmarkTaxonomyVersion: z.literal("benchmark-radar-v2"), data: z.object({ sourceContext: context.extend({ playerId: z.number().int().positive(), idNamespace: z.literal("fotmob") }), benchmarkContext: context.extend({ label: z.literal("8-league avg") }), positionReference: z.object({ rawPosition: z.string().min(1), comparisonKey: z.string().min(1), minimumPopulation: z.number().int().positive(), population: z.number().int().nonnegative(), state: z.enum(["observed", "low_sample", "unavailable"]), reason: z.string().nullable() }).strict(), volume: series, ratio: series }).strict() }).strict();
export type BenchmarkRadarV2 = z.infer<typeof benchmarkRadarV2EnvelopeSchema>["data"];
