import type { MessiApiConfig } from "./env";
import { duelPressV2DetailMetricsSchema, duelPressV2LeaderboardSchema, duelPressV2PlayerSchema, type DuelPressV2Context, type DuelPressV2DetailMetrics, type DuelPressV2Leaderboard, type DuelPressV2Player } from "./duelPressV2Contracts";
import type { DatasetRouteState } from "../dashboard/types";
import { adaptDuelPressV2PlayerCore } from "./duelPressAdapter";
import type { DuelPressLeaderboardPayload, DuelPressSearch } from "./duelPressTypes";

export type DuelPressV2ErrorKind = "not-found" | "invalid-request" | "schema" | "network";
export class DuelPressV2ApiError extends Error { constructor(public readonly kind: DuelPressV2ErrorKind, message: string = kind) { super(message); this.name = "DuelPressV2ApiError"; } }
const statusError = (status: number) => new DuelPressV2ApiError(status === 404 ? "not-found" : status === 422 ? "invalid-request" : "network", `Duel/Press v2 request failed (${status})`);
const positiveId = (id: number) => { if (!Number.isSafeInteger(id) || id <= 0) throw new DuelPressV2ApiError("invalid-request", "playerId must be a positive safe integer"); };
export const duelPressV2Context = (state: DatasetRouteState): DuelPressV2Context => state.mode === "league" ? { playerId: 1, season: state.season, mode: "league", scope: state.scope, competition: null, idNamespace: "fotmob" } : { playerId: 1, season: state.season, mode: "europe", scope: null, competition: state.competition, idNamespace: "fotmob" };
function addContext(url: URL, context: DuelPressV2Context, includePlayer = false) {
  url.searchParams.set("season", context.season); url.searchParams.set("mode", context.mode);
  if (context.mode === "league") { url.searchParams.set("scope", String(context.scope)); url.searchParams.set("competition", "all"); } else if (context.competition) url.searchParams.set("competition", context.competition);
  if (includePlayer) url.searchParams.set("playerId", String(context.playerId));
}
export function buildDuelPressV2LeaderboardUrl(baseUrl: string, state: DatasetRouteState, query: Record<string, string | number | undefined>): string { const url = new URL("/api/v2/leaderboards/duel-press-v2", baseUrl); addContext(url, duelPressV2Context(state)); for (const [key, value] of Object.entries({ ...query, pageSize: 50 })) if (value !== undefined) url.searchParams.set(key, String(value)); return url.toString(); }
export function buildDuelPressV2PlayerUrl(baseUrl: string, playerId: number, state: DatasetRouteState): string { positiveId(playerId); const url = new URL(`/api/v2/players/${playerId}/duel-press-v2`, baseUrl); addContext(url, duelPressV2Context(state)); return url.toString(); }
export function buildDuelPressV2DetailMetricsUrl(baseUrl: string, playerId: number, state: DatasetRouteState): string { positiveId(playerId); const url = new URL(`/api/v2/players/${playerId}/duel-press-v2/detail-metrics`, baseUrl); addContext(url, duelPressV2Context(state)); return url.toString(); }
async function getJson(url: string, signal: AbortSignal): Promise<unknown> { let response: Response; try { response = await fetch(url, { method: "GET", credentials: "omit", headers: { Accept: "application/json" }, signal }); } catch (error) { if (signal.aborted) throw error; throw new DuelPressV2ApiError("network", "Unable to reach the Duel/Press v2 API"); } if (!response.ok) throw statusError(response.status); try { return await response.json(); } catch { throw new DuelPressV2ApiError("schema", "Duel/Press v2 response was not valid JSON"); } }
export const duelPressV2ResourceKey = (endpoint: string, playerId: number, state: DatasetRouteState, ratingSnapshotId = "") => JSON.stringify(["duel-press-v2", endpoint, playerId, state.season, state.mode, state.mode === "league" ? state.scope : null, state.mode === "league" ? "all" : state.competition, ratingSnapshotId]);
export async function fetchDuelPressV2DetailMetrics(config: MessiApiConfig, playerId: number, state: DatasetRouteState, signal: AbortSignal): Promise<DuelPressV2DetailMetrics> { const parsed = duelPressV2DetailMetricsSchema.safeParse(await getJson(buildDuelPressV2DetailMetricsUrl(config.baseUrl, playerId, state), signal)); if (!parsed.success) throw new DuelPressV2ApiError("schema", "Duel/Press v2 detail-metrics response violated the strict contract"); const expected = duelPressV2Context(state); if (parsed.data.context.playerId !== playerId || parsed.data.context.idNamespace !== "fotmob" || parsed.data.context.season !== expected.season || parsed.data.context.mode !== expected.mode || parsed.data.context.scope !== (state.mode === "league" ? state.scope : null) || parsed.data.context.competition !== (state.mode === "league" ? null : state.competition)) throw new DuelPressV2ApiError("schema", "Duel/Press v2 detail context did not match request"); return parsed.data; }
export async function fetchDuelPressV2Player(config: MessiApiConfig, playerId: number, state: DatasetRouteState, signal: AbortSignal): Promise<DuelPressV2Player> { const parsed = duelPressV2PlayerSchema.safeParse(await getJson(buildDuelPressV2PlayerUrl(config.baseUrl, playerId, state), signal)); if (!parsed.success) throw new DuelPressV2ApiError("schema", "Duel/Press v2 player response violated the strict contract"); if (parsed.data.context.playerId !== playerId || parsed.data.context.season !== state.season || parsed.data.context.mode !== state.mode) throw new DuelPressV2ApiError("schema", "Duel/Press v2 player context did not match request"); return parsed.data; }
export async function fetchDuelPressV2Leaderboard(config: MessiApiConfig, state: DatasetRouteState, query: Record<string, string | number | undefined>, signal: AbortSignal): Promise<DuelPressV2Leaderboard> { const parsed = duelPressV2LeaderboardSchema.safeParse(await getJson(buildDuelPressV2LeaderboardUrl(config.baseUrl, state, query), signal)); if (!parsed.success) throw new DuelPressV2ApiError("schema", "Duel/Press v2 leaderboard response violated the strict contract"); if (parsed.data.meta.page !== Number(query.page ?? 1) || parsed.data.meta.pageSize !== 50 || parsed.data.meta.season !== state.season || parsed.data.meta.mode !== state.mode || parsed.data.context.scope !== (state.mode === "league" ? state.scope : null) || parsed.data.context.competition !== (state.mode === "league" ? null : state.competition)) throw new DuelPressV2ApiError("schema", "Duel/Press v2 leaderboard metadata did not match request"); return parsed.data; }
export async function fetchDuelPressV2LeaderboardPayload(config: MessiApiConfig, state: DatasetRouteState, search: DuelPressSearch, signal: AbortSignal): Promise<DuelPressLeaderboardPayload> {
  const response = await fetchDuelPressV2Leaderboard(config, state, { page: search.page, sort: search.sort, order: search.direction, q: search.q || undefined, role: search.role === "all" ? undefined : search.role, position: search.position === "ALL" ? undefined : search.position, ageBand: search.ageBand === "all" ? undefined : search.ageBand, minutesBand: search.minutesBand === "all" ? undefined : search.minutesBand }, signal);
  return { players: response.data.map(adaptDuelPressV2PlayerCore), meta: { schemaVersion: "1.1.0", season: response.meta.season, mode: response.meta.mode, scope: response.meta.scope, competition: response.meta.competition, population: response.meta.population, returned: response.meta.returned, page: response.meta.page, pageSize: 50, totalItems: response.meta.totalItems, totalPages: response.meta.totalPages, hasNextPage: response.meta.hasNextPage, applied: response.meta.applied as never, generatedAt: response.meta.generatedAt, source: "messi-static-cohort" }, serverPage: { page: response.meta.page, pageSize: 50, totalPages: response.meta.totalPages, hasNextPage: response.meta.hasNextPage } };
}
