import { describe, expect, it } from "vitest";
import { detailReadoutFixture } from "../test/fixtures/duelPressDetailReadouts";
import { duelPressDetailReadoutEnvelopeSchema } from "./duelPressDetailReadoutContracts";

describe("detail-readout-v1 strict contract", () => {
  it("accepts the released Kane static-record-shaped fixture, including a real zero", () => { expect(duelPressDetailReadoutEnvelopeSchema.safeParse(detailReadoutFixture).success).toBe(true); });
  it("rejects version, extra fields, order, duplicated IDs, and a mismatched identity", () => { const bad = (patch: object) => expect(duelPressDetailReadoutEnvelopeSchema.safeParse({ ...detailReadoutFixture, ...patch }).success).toBe(false); bad({ readoutVersion: "detail-readout-v2" }); bad({ extra: true }); bad({ categories: [...detailReadoutFixture.categories].reverse() }); bad({ contextIndicators: [detailReadoutFixture.contextIndicators[1], detailReadoutFixture.contextIndicators[0]] }); bad({ player: { ...detailReadoutFixture.player, id: 7 } }); });
  it("rejects an unavailable numeric value and bad formula pairing", () => { const categories = structuredClone(detailReadoutFixture.categories); categories[0].readouts[0] = { ...categories[0].readouts[0], value: null, state: "unavailable", source: "unavailable" }; expect(duelPressDetailReadoutEnvelopeSchema.safeParse({ ...detailReadoutFixture, categories }).success).toBe(false); const indicators = structuredClone(detailReadoutFixture.contextIndicators); indicators[0] = { ...indicators[0], formulaVersion: null }; expect(duelPressDetailReadoutEnvelopeSchema.safeParse({ ...detailReadoutFixture, contextIndicators: indicators }).success).toBe(false); });
  it("preserves released observed-zero and imputed/unavailable semantics", () => { const zero = structuredClone(detailReadoutFixture); zero.context.playerId = 846381; zero.player.id = 846381; zero.categories[0].readouts[2] = { ...zero.categories[0].readouts[2], id: "outsideBoxXgot", value: 0, state: "observed", source: "player_season_total", formulaId: null, formulaVersion: null }; expect(duelPressDetailReadoutEnvelopeSchema.safeParse(zero).success).toBe(true); const unavailable = structuredClone(detailReadoutFixture); unavailable.context.playerId = 174031; unavailable.player.id = 174031; const press = unavailable.categories[5]; press.scoreState = "imputed"; press.imputedComponents = ["final_third_possessions_won"];
    const unavailableComparison = { state: "unavailable", median: 1, rank: null, percentile: null, population: 20 }; press.readouts[2] = { ...press.readouts[2], value: null, state: "unavailable", source: "unavailable", comparison: unavailableComparison, formulaId: null, formulaVersion: null }; press.readouts[3] = { ...press.readouts[3], value: null, state: "unavailable", source: "unavailable", comparison: unavailableComparison, formulaId: null, formulaVersion: null }; const parsed = duelPressDetailReadoutEnvelopeSchema.safeParse(unavailable); if (!parsed.success) throw new Error(parsed.error.issues.map((issue) => issue.message).join("; ")); expect(parsed.success).toBe(true); });
});
