import { afterEach, describe, expect, it, vi } from "vitest";
import { detailReadoutFixture } from "../test/fixtures/duelPressDetailReadouts";
import { buildDuelPressDetailReadoutUrl, fetchDuelPressDetailReadouts } from "./duelPressDetailReadoutApi";
const config = { baseUrl: "https://api.test", season: "2025/2026", scope: 8 as const, limit: 1000 };
afterEach(() => vi.unstubAllGlobals());
describe("detail readout transport", () => {
  it("serializes league and Europe contexts canonically", () => { const league = new URL(buildDuelPressDetailReadoutUrl(config.baseUrl, 194165, { season: "2025/2026", mode: "league", scope: 8, competition: "all" })); expect(league.searchParams.get("scope")).toBe("8"); expect(league.searchParams.get("competition")).toBe("all"); const europe = new URL(buildDuelPressDetailReadoutUrl(config.baseUrl, 194165, { season: "2025/2026", mode: "europe", scope: null, competition: "ucl" })); expect(europe.searchParams.has("scope")).toBe(false); expect(europe.searchParams.get("competition")).toBe("ucl"); });
  it("classifies HTTP and schema failures", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("", { status: 404 }))); await expect(fetchDuelPressDetailReadouts(config, 194165, { season: "2025/2026", mode: "league", scope: 8, competition: "all" }, new AbortController().signal)).rejects.toMatchObject({ kind: "not-found" }); vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ ...detailReadoutFixture, readoutVersion: "wrong" }), { status: 200 }))); await expect(fetchDuelPressDetailReadouts(config, 194165, { season: "2025/2026", mode: "league", scope: 8, competition: "all" }, new AbortController().signal)).rejects.toMatchObject({ kind: "schema" }); });
  it("rejects a schema-valid response whose echoed request identity differs", async () => { const otherContext = { ...detailReadoutFixture, context: { ...detailReadoutFixture.context, season: "2024/2025" } }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify(otherContext), { status: 200 }))); await expect(fetchDuelPressDetailReadouts(config, 194165, { season: "2025/2026", mode: "league", scope: 8, competition: "all" }, new AbortController().signal)).rejects.toMatchObject({ kind: "schema" }); });
});
