import { afterEach, describe, expect, it, vi } from "vitest";
import { fetchVolumeBenchmark } from "./volumeBenchmarkApi";
import { benchmarkEnvelope } from "../test/volumeBenchmarkFixtures";
const config = { baseUrl: "https://api.example.test", season: "2025/2026", scope: 8 as const, limit: 1000 };
afterEach(() => vi.restoreAllMocks());
describe("volume benchmark API", () => {
  it("builds exact league and Europe URLs", async () => { const request = vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify(benchmarkEnvelope),{headers:{"Content-Type":"application/json"}})); await fetchVolumeBenchmark(config,1,{season:"2025/2026",mode:"league",scope:8,competition:"all"},new AbortController().signal); const league = new URL(String(request.mock.calls[0][0])); expect(league.searchParams.get("scope")).toBe("8"); expect(league.searchParams.get("competition")).toBe("all"); expect(league.searchParams.get("benchmarkScope")).toBe("8"); request.mockResolvedValueOnce(new Response(JSON.stringify({ ...benchmarkEnvelope, data: { ...benchmarkEnvelope.data, sourceContext: { mode:"europe",scope:null,competition:"ucl" } } }),{headers:{"Content-Type":"application/json"}})); await fetchVolumeBenchmark(config,1,{season:"2025/2026",mode:"europe",scope:8,competition:"ucl"},new AbortController().signal); const europe = new URL(String(request.mock.calls[1][0])); expect(europe.searchParams.has("scope")).toBe(false); expect(europe.searchParams.get("competition")).toBe("ucl"); });
  it("classifies 422 and rejects identity mismatches", async () => { vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(new Response("",{status:422})).mockResolvedValueOnce(new Response(JSON.stringify({ ...benchmarkEnvelope, data:{...benchmarkEnvelope.data,playerId:2} }),{headers:{"Content-Type":"application/json"}})); await expect(fetchVolumeBenchmark(config,1,{season:"2025/2026",mode:"league",scope:8,competition:"all"},new AbortController().signal)).rejects.toMatchObject({kind:"http",status:422}); await expect(fetchVolumeBenchmark(config,1,{season:"2025/2026",mode:"league",scope:8,competition:"all"},new AbortController().signal)).rejects.toMatchObject({kind:"schema"}); });
});
